In [20]:
import pandas as pd

In [21]:
data = pd.read_csv('stat_list_with_result.csv')

In [23]:
data.count()

Unnamed: 0                         4476
away-accurate_back_zone_pass-1     4466
away-accurate_back_zone_pass-2     4456
away-accurate_back_zone_pass-3     4447
away-accurate_chipped_pass-1       4455
away-accurate_chipped_pass-2       4437
away-accurate_chipped_pass-3       4419
away-accurate_corners_intobox-1    3395
away-accurate_corners_intobox-2    3250
away-accurate_corners_intobox-3    3290
away-accurate_cross-1              4398
away-accurate_cross-2              4362
away-accurate_cross-3              4359
away-accurate_cross_nocorner-1     4246
away-accurate_cross_nocorner-2     4147
away-accurate_cross_nocorner-3     4179
away-accurate_freekick_cross-1     1254
away-accurate_freekick_cross-2     1167
away-accurate_freekick_cross-3     1165
away-accurate_fwd_zone_pass-1      4466
away-accurate_fwd_zone_pass-2      4456
away-accurate_fwd_zone_pass-3      4447
away-accurate_goal_kicks-1         4361
away-accurate_goal_kicks-2         4362
away-accurate_goal_kicks-3         4350
away-accurate_keeper_throws-1      4205
away-accurate_keeper_throws-2      4187
away-accurate_keeper_throws-3      4199
away-accurate_long_balls-1         4466
away-accurate_long_balls-2         4456
                                   ...
home-total_tackle-1                4467
home-total_tackle-2                4458
home-total_tackle-3                4448
home-total_throws-1                4467
home-total_throws-2                4458
home-total_throws-3                4448
home-total_yel_card-1              3688
home-total_yel_card-2              3525
home-total_yel_card-3              3597
home-touches-1                     4467
home-touches-2                     4458
home-touches-3                     4448
home-unsuccessful_touch-1          3318
home-unsuccessful_touch-2          3301
home-unsuccessful_touch-3          3282
home-wins-1                        1426
home-wins-2                        1745
home-wins-3                        1668
home-won_contest-1                 4444
home-won_contest-2                 4437
home-won_contest-3                 4421
home-won_corners-1                 4376
home-won_corners-2                 4387
home-won_corners-3                 4369
home-won_tackle-1                  4466
home-won_tackle-2                  4458
home-won_tackle-3                  4447
home_team                          4476
match_id                           4476
result                             4476
Length: 1156, dtype: int64

In [11]:
data.describe()

,Unnamed: 0,away-accurate_back_zone_pass-1,away-accurate_back_zone_pass-2,away-accurate_back_zone_pass-3,away-accurate_chipped_pass-1,away-accurate_chipped_pass-2,away-accurate_chipped_pass-3,away-accurate_corners_intobox-1,away-accurate_corners_intobox-2,away-accurate_corners_intobox-3,...,home-won_contest-1,home-won_contest-2,home-won_contest-3,home-won_corners-1,home-won_corners-2,home-won_corners-3,home-won_tackle-1,home-won_tackle-2,home-won_tackle-3,match_id
count,4476.000000,4466.000000,4456.000000,4447.000000,4455.000000,4437.000000,4419.000000,3395.000000,3250.000000,3290.000000,...,4444.000000,4437.000000,4421.000000,4376.000000,4387.000000,4369.000000,4466.000000,4458.000000,4447.000000,4476.000000
mean,2237.500000,148.499328,147.570467,147.721610,15.464198,14.949065,15.103417,2.094256,2.035077,2.047112,...,7.860036,8.199008,8.044334,5.241773,5.620242,5.572442,14.431482,14.318977,14.364965,11951.614388
std,1292.254232,58.418885,59.139804,58.110082,6.329808,6.142809,6.171675,1.214943,1.187293,1.218547,...,4.110530,4.259485,4.192735,2.852496,2.987026,2.929315,5.032560,5.036025,5.115241,8344.598846
min,0.000000,30.000000,32.000000,30.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,5947.000000
25%,1118.750000,104.000000,103.000000,104.000000,11.000000,11.000000,11.000000,1.000000,1.000000,1.000000,...,5.000000,5.000000,5.000000,3.000000,3.000000,3.000000,11.000000,11.000000,11.000000,7065.750000
50%,2237.500000,143.000000,141.000000,141.000000,15.000000,14.000000,15.000000,2.000000,2.000000,2.000000,...,7.000000,8.000000,8.000000,5.000000,5.000000,5.000000,14.000000,14.000000,14.000000,8201.500000
75%,3356.250000,184.000000,184.000000,184.000000,19.000000,19.000000,19.000000,3.000000,3.000000,3.000000,...,10.000000,11.000000,10.000000,7.000000,7.000000,7.000000,17.000000,17.000000,17.000000,12431.250000
max,4475.000000,401.000000,493.000000,423.000000,45.000000,52.000000,45.000000,8.000000,9.000000,8.000000,...,33.000000,28.000000,33.000000,19.000000,19.000000,19.000000,40.000000,39.000000,40.000000,38607.000000

In [12]:
import numpy as np
data = data.replace('np.nan', 0)

In [13]:
data.info()

,Unnamed: 0,away-accurate_back_zone_pass-1,away-accurate_back_zone_pass-2,away-accurate_back_zone_pass-3,away-accurate_chipped_pass-1,away-accurate_chipped_pass-2,away-accurate_chipped_pass-3,away-accurate_corners_intobox-1,away-accurate_corners_intobox-2,away-accurate_corners_intobox-3,...,home-won_contest-1,home-won_contest-2,home-won_contest-3,home-won_corners-1,home-won_corners-2,home-won_corners-3,home-won_tackle-1,home-won_tackle-2,home-won_tackle-3,match_id
count,4476.000000,4466.000000,4456.000000,4447.000000,4455.000000,4437.000000,4419.000000,3395.000000,3250.000000,3290.000000,...,4444.000000,4437.000000,4421.000000,4376.000000,4387.000000,4369.000000,4466.000000,4458.000000,4447.000000,4476.000000
mean,2237.500000,148.499328,147.570467,147.721610,15.464198,14.949065,15.103417,2.094256,2.035077,2.047112,...,7.860036,8.199008,8.044334,5.241773,5.620242,5.572442,14.431482,14.318977,14.364965,11951.614388
std,1292.254232,58.418885,59.139804,58.110082,6.329808,6.142809,6.171675,1.214943,1.187293,1.218547,...,4.110530,4.259485,4.192735,2.852496,2.987026,2.929315,5.032560,5.036025,5.115241,8344.598846
min,0.000000,30.000000,32.000000,30.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,5947.000000
25%,1118.750000,104.000000,103.000000,104.000000,11.000000,11.000000,11.000000,1.000000,1.000000,1.000000,...,5.000000,5.000000,5.000000,3.000000,3.000000,3.000000,11.000000,11.000000,11.000000,7065.750000
50%,2237.500000,143.000000,141.000000,141.000000,15.000000,14.000000,15.000000,2.000000,2.000000,2.000000,...,7.000000,8.000000,8.000000,5.000000,5.000000,5.000000,14.000000,14.000000,14.000000,8201.500000
75%,3356.250000,184.000000,184.000000,184.000000,19.000000,19.000000,19.000000,3.000000,3.000000,3.000000,...,10.000000,11.000000,10.000000,7.000000,7.000000,7.000000,17.000000,17.000000,17.000000,12431.250000
max,4475.000000,401.000000,493.000000,423.000000,45.000000,52.000000,45.000000,8.000000,9.000000,8.000000,...,33.000000,28.000000,33.000000,19.000000,19.000000,19.000000,40.000000,39.000000,40.000000,38607.000000

In [18]:
for row in data:
    data[row].fillna(0, inplace=True)